service: ppp-portal

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  region: ap-east-1
  runtime: python3.9
  iam:
    role:
      managedPolicies:
        - arn:aws:iam::694855297262:policy/PalWorld-202402

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'
  pppstatus:
    handler: asyncc.pppstatus

plugins:
  - serverless-wsgi
  - serverless-python-requirements
